services:
  postgres:
    image: postgres:18.1
    container_name: birthdays_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: birthdays_app
      POSTGRES_PASSWORD: birthdays_app
      POSTGRES_DB: birthdays_db
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "55432:5432"
    volumes:
      - birthdays_db_data:/var/lib/postgresql

volumes:
  birthdays_db_data: